version: '3.6'
services:
  db:
    image: mariadb:10.6.4-focal
    container_name: mariadb
    ports:
      - 3306:3306
    volumes:
      - C:\ProgramData\MySQL\MySQL Server 5.5\data\test:./mariadb_data
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: test
        MYSQL_USER: root
        MYSQL_PASSWORD: root
    restart: always
  app:
    image: papoff/microservice1
    container_name: microService1
    ports:
      - 8080:3000
    environment:
      mariadb_host: db
    restart: always
    links:
      - db
#  nginx:
#    image: nginx:1.21.1
#    container_name: nginx
#    volumes:
#      - ./default.conf:/etc/nginx/conf.d/default.conf
#    links:
#      - app
#    ports:
#      - 8989:8989